default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: andrestephano_development
  username: root
  password: pass

test:
  <<: *default
  database: andrestephano_test
  username: root
  password: pass

production:
  <<: *default
  database: andrestephano_production
  username: andrestephano
  password: <%= ENV['ANDRESTEPHANO_DATABASE_PASSWORD'] %>
